version: "3"
services:
    db:
        container_name: postgres
        image: postgres
        restart: always
        ports:
            - "5432:5432"
        environment:
            POSTGRES_PASSWORD: example
            POSTGRES_DB: frank
