version: "3"
services:
    db:
        container_name: dynamo
        image: amazon/dynamodb-local
        restart: always
        ports:
            - "8000:8000"
    redis:
        image: redis
        ports:
            - 6379:6379
    app:
        build: .
        ports:
            - 8088:8088

